apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-frontend
  labels:
    app: customer-management-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management-frontend
  template:
    metadata:
      labels:
        app: customer-management-frontend
    spec:
      containers:
        - name: customer-management-frontend
          image: lakesidemutual/customer-management-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: REACT_APP_CUSTOMER_SELF_SERVICE_BACKEND
              value: http://customer-self-service-backend:8080
            - name: REACT_APP_CUSTOMER_MANAGEMENT_BACKEND
              value: http://customer-management-backend:8100
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: customer-management-frontend
spec:
  type: ClusterIP
  selector:
    app: customer-management-frontend
  ports:
    - name: "3020"
      port: 3020
      targetPort: 80
