apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-management-frontend
  labels:
    app: policy-management-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-management-frontend
  template:
    metadata:
      labels:
        app: policy-management-frontend
    spec:
      containers:
        - name: policy-management-frontend
          image: lakesidemutual/policy-management-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: VUE_APP_POLICY_MANAGEMENT_BACKEND
              value: http://policy-management-backend:8090
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: policy-management-frontend
spec:
  type: ClusterIP
  selector:
    app: policy-management-frontend
  ports:
    - name: "3010"
      port: 3010
      targetPort: 80
